---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasne-exporter-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasne-exporter
  template:
    metadata:
      labels:
        app: nasne-exporter
    spec:
      containers:
      - name: nasne-exporter
        image: quay.io/hatotaka/nasne-exporter
        ports:
        - containerPort: 8080
